# Generated by Django 4.2.3 on 2023-07-11 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TravelApp', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Pic', models.ImageField(upload_to='Pics')),
                ('Name', models.CharField(max_length=20)),
                ('Dis', models.TextField()),
            ],
        ),
    ]
